classDiagram
    ResourceType "1" -- "1..*" Resource
    Resource "1" -- "0..*" Booking
    Booking "1" -- "1..*" Person
    
    class ResourceType{
      Id
      Enheder
      Title
      Krav
    }
    class Resource{
      Id
      Titel
      Pris
      Beskrivelse
      ErAktiv
    }
    class Booking{
      Id
      StartTid
      SlutTid
      KravStatus
      Betalingsstatus
      Udleveret
      Retunert
    }
    class Person{
      Id
      Navn
      Email
      TelefonNr
    }