sequenceDiagram
    actor Administrator
    Administrator->>AdminSystem: FindResource
    AdminSystem-->>Administrator: ResourceDetaljer
    Administrator->>AdminSystem: RetOplysninger
    AdminSystem-->>Administrator: BekræftOpdatering